## The second In-class-exercise (09/22/2022, 40 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [57]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Using the most selling item in the world!
That is non other than Collecting the Harry Potter Box Set: The Complete Collection (Children's Paperback)
This is the most selling item all over the world!
Here, we have considering the data set that neede to be analysis of the ratings and the review of that data.
Kepping the customers reviews in mind!



'''

"\nPlease write you answer here:\n\nUsing the most selling item in the world!\nThat is non other than Collecting the Harry Potter Box Set: The Complete Collection (Children's Paperback)\nThis is the most selling item all over the world!\nHere, we have considering the data set that neede to be analysis of the ratings and the review of that data.\nKepping the customers reviews in mind!\n\n\n\n"

Question 2 (10 points): Write python code to collect 1000 data samples you discussed above.

In [15]:
# You code here (Please add comments in the code):

import requests
from bs4 import BeautifulSoup
import pandas as pd
Rating = [] # List to store Review headings
Review =[] #List to store reviews
Rev_place =[]

#Collecting the Harry Potter Box Set: The Complete Collection (Children's Paperback) Reviews from Flipkart
for number in range(100):
  requested_link = "https://www.flipkart.com/harry-potter-box-set-complete-collection-children-s-paperback/product-reviews/itma23355d0b5e66?pid=9781408856772&lid=LSTBOK9781408856772SQ5QLG&marketplace=FLIPKART" + str(number) # Generating link dynamically
  #Getting Request for the link above
  web_page = requests.get(requested_link)
  soup = BeautifulSoup(web_page.text, 'html.parser')
  rating_reviews = soup.find_all(class_='_3LWZlK _1BLPMq')
  text_reviews = soup.find_all(class_='_2-N8zT')
  review_place =soup.find_all(class_='_2mcZGG')
  for ele, sub_ele,rev_pl in zip(rating_reviews, text_reviews, review_place) : # Iterating through the list
      Rating.append(ele.text) #Appending to empty list
      Review.append(sub_ele.text)
      Rev_place.append(rev_pl.text)

#Dataframe Creation by combining collected data and making the column names of our own!
harry_potter = pd.DataFrame(list(zip(Rating, Review,Rev_place )), columns =['Rating', 'Short Review', 'Place']) 
print("Total Data Frame Length is {0}".format(len(harry_potter)))

harry_potter

Total Data Frame Length is 1000

,Rating,Short Review,Place
0,5,Worth every penny,"Certified Buyer, Ahmedabad"
1,5,Just wow!,"Certified Buyer, Hassan"
2,5,Mind-blowing purchase,"Certified Buyer, Muzaffarpur"
3,5,Fabulous!,"Certified Buyer, Nanded"
4,5,IT'S GORGEOUS.,"Certified Buyer, Kolkata"
...,...,...,...
995,5,Perfect product!,"Certified Buyer, Ernakulam"
996,5,Perfect product!,"Certified Buyer, Dehradun"
997,5,Terrific,"Certified Buyer, Lucknow"
998,5,Mind-blowing purchase,"Certified Buyer, North Twenty Four Parganas Di..."
999,5,Must buy!,"Certified Buyer, Santoshpur"

Question 3 (10 points): Write python code to collect 1000 articles from Google Scholar (https://scholar.google.com/), Microsoft Academic (https://academic.microsoft.com/home), or CiteSeerX (https://citeseerx.ist.psu.edu/index), or Semantic Scholar (https://www.semanticscholar.org/), or ACM Digital Libraries (https://dl.acm.org/) with the keyword "information retrieval". The articles should be published in the last 10 years (2012-2022).

The following information of the article needs to be collected:

(1) Title

(2) Venue/journal/conference being published

(3) Year

(4) Authors

(5) Abstract

In [55]:
# You code here (Please add comments in the code):
from bs4 import BeautifulSoup
import requests, lxml, os, json
import pandas as pd
headers = {
    'User-agent':
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582"
}
params = {
  "q": "Information retrival",
  "hl": "en",
}
google_link = requests.get('https://scholar.google.com/scholar?as_ylo=2018&q=%22information+retrieval%22&hl=en&as_sdt=0,44', headers=headers, params = params).text
soup = BeautifulSoup(google_link, 'lxml')
for pdf in soup.select('.gs_or_ggsm a'):
  scholar_link = pdf['href']
  print(scholar_link)
  list_of_data = []
for result in soup.select('.gs_ri'):
  Article_title = result.select_one('.gs_rt').text
  Article_Publication = result.select_one('.gs_a').text
  Article_abstract = result.select_one('.gs_rs').text
  try:
    version_of_articles = result.select_one('a~ a+ .gs_nph')['href']
  except:
    version_of_articles = None
  data = {
      'Title': Article_title,
      'Authors(Venue/journal) publishedYear': Article_Publication,
      'Abstract': Article_abstract
  }
  list_of_data.append(data)
scholar_data = pd.DataFrame(list_of_data)
scholar_data


#ref link: https://dev.to/dmitryzub/scrape-google-scholar-with-python-32oh

https://onlinelibrary.wiley.com/doi/pdf/10.1111/hir.12276
/scholar?output=instlink&q=info:tqiKO1QsWrkJ:scholar.google.com/&hl=en&as_sdt=0,44&as_ylo=2018&scillfp=993035561631326653&oi=lle
https://www.researchgate.net/profile/Feng-Xia-7/publication/336962150_Data_Mining_and_Information_Retrieval_in_the_21st_century_A_bibliographic_review/links/5f2e8abf92851cd302e7e10b/Data-Mining-and-Information-Retrieval-in-the-21st-century-A-bibliographic-review.pdf
https://arxiv.org/pdf/1903.06902
https://repository.ubn.ru.nl/bitstream/handle/2066/199898/3/199898.pdf
https://www.nowpublishers.com/article/DownloadSummary/INR-065
https://arxiv.org/pdf/2002.06612
https://arxiv.org/pdf/2112.09118
https://www.nowpublishers.com/article/DownloadSummary/INR-063
https://www.researchgate.net/profile/Zongda-Wu/publication/339448275_A_dummy-based_user_privacy_protection_approach_for_text_information_retrieval/links/61a5798a8c253c45f69783d8/A-dummy-based-user-privacy-protection-approach-for-text-information-retrieval.pdf
https://arxiv.org/pdf/1912.05891

,Title,Authors(Venue/journal) publishedYear,Abstract
0,Meeting the review family: exploring review ty...,"A Sutton, M Clowes, L Preston… - Health Inform...",… This study aims to characterise health relat...
1,Data Mining and Information Retrieval in the 2...,"J Liu, X Kong, X Zhou, L Wang, D Zhang, I Lee…...","… in mathematics, statistics, information scie..."
2,A deep look into neural ranking models for inf...,"J Guo, Y Fan, L Pang, L Yang, Q Ai, H Zamani… ...",Ranking models lie at the heart of research on...
3,Research frontiers in information retrieval: R...,"JS Culpepper, F Diaz, MD Smucker - ACM SIGIR F...",… -range issues of the Information Retrieval f...
4,Information retrieval: the early years,D Harman - … and Trends® in Information Retrie...,… This monograph traces the evolution of infor...
5,Text‐based question answering from information...,"Z Abbasiantaeb, S Momtazi - Wiley Interdiscipl...",… This line of research has been widely studie...
6,Towards unsupervised dense information retriev...,"G Izacard, M Caron, L Hosseini, S Riedel… - ar...","… In this section, we briefly review relevant ..."
7,Knowledge graphs: An information retrieval per...,"R Reinanda, E Meij, M de Rijke - … ® in Inform...","In this survey, we provide an overview of the ..."
8,A dummy-based user privacy protection approach...,"Z Wu, S Shen, X Lian, X Su, E Chen - Knowledge...",… Text retrieval enables people to efficiently...
9,Setrank: Learning a permutation-invariant rank...,"L Pang, J Xu, Q Ai, Y Lan, X Cheng, J Wen - … ...",… In learning-to-rank for information retrieva...

Question 4 (10 points): Write python code to collect 1000 posts from Twitter, or Facebook, or Instagram. You can either use hashtags, keywords, user_name, user_id, or other information to collect the data. 

The following information needs to be collected:

(1) User_name

(2) Posted time

(3) Text

In [48]:
import os
import tweepy 
import pandas as pd

customer_key ="2Em7SxlX9jPMfL4x97r3zMO0x"
customer_secret = "sVbJzekKuiAgq83Y7gCwNVbSowqQokGVzWexKHl2cXIPceWtSd"
access_token ="1439767876962029572-uUMt8oWRyzj9ilE5zk4uYbL93sCMPT"
access_token_secret = "oydIGymn9bS767FVEMawE9GyGAnMmBJfaY2XXKmHnmliF"

auth = tweepy.OAuthHandler(customer_key, customer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

username =str(input("Enter twitter username\t"))

tweets_ex = tweepy.Cursor(api.user_timeline,id=username).items(1000)

tweets_list_ex = [[username ,tweet.created_at, tweet.text] for tweet in tweets_ex]

tweets_ex_df = pd.DataFrame(tweets_list_ex)
tweets_ex_df.columns=['user_name','posted time','text']
tweets_ex_df

Enter twitter username	icc

,user_name,posted time,text
0,icc,2022-09-26 04:29:38,"""One of the greatest ever to play the sport"" 🗣..."
1,icc,2022-09-26 04:01:38,Tournament winners 🎉\n\nBangladesh cap off the...
2,icc,2022-09-26 03:30:39,Do Tim David and Steve Smith both make Austral...
3,icc,2022-09-26 02:26:12,A record for the rising Cameron Green!\n\nIndi...
4,icc,2022-09-26 00:55:53,What it means for Bangladesh to win the Women'...
...,...,...,...
995,icc,2022-08-17 02:00:30,Shikhar Dhawan credits India's domestic league...
996,icc,2022-08-17 01:16:20,Mohammad Nabi will captain a strong 17-player ...
997,icc,2022-08-17 00:03:05,Key points from the historic first-ever Women'...
998,icc,2022-08-16 17:28:07,Pakistan go 1-0 up in the ODI series 👏 \n\nNet...
999,icc,2022-08-16 16:30:05,Celebrating the unparalleled legacy of Kevin O...